#!/bin/sh

FZF_IMAGES_CLIENT="podman"
FZF_IMAGES_TAGS_REGISTRY_DIR=/tmp/.fzf_images_cache
FZF_IMAGES_ENTRIES=("tar"
                    "local")
AWS_REGION="us-east-1" # set with tmux setenv outside of the script

# ! bat preview show list of images
# ! bat preview show info of the registry
# ! bind action to go back to menu
_fzf_images_menu(){ 
  REGISTRIES=$(_fzf_images_get_registry)
  FZF_IMAGES_ENTRIES=("${FZF_IMAGES_ENTRIES[@]}" "${REGISTRIES[@]}")
  _fzf_images_entry_selection \
    $(printf "%s\n" "${FZF_IMAGES_ENTRIES[@]}" | fzf-tmux -p) 
}

# ! run selection on tmux-fzf or another window and send to previous pane
_fzf_images_entry_selection(){ 
  if [ ! -z "$1" ]; then 
    case $1 in
      "tar")
        _fzf_images_fzf_tar ;;
      "local")
        _fzf_images_fzf_local ;;
      *)
        _fzf_images_fzf_registry $1 ;;
    esac
  fi
}

#####################
### ENTRIES
#####################

# ! scan with trivy
# ! preview inspect
_fzf_images_fzf_registry(){
  tmux setenv FZF_IMAGES_REGISTRY $1
  _fzf_images_tags_registry $1 | fzf \
    --multi \
    --header-lines=1 \
      --bind 'enter:execute-silent(sh fzf_images _fzf_images_action_run /{1}:{2})+abort'
  tmux setenv -u FZF_IMAGES_REGISTRY
}

_fzf_images_fzf_tar(){
  find . -iname "*.tar" | sed '1i TAR' | column -t | fzf \
    --multi \
    --header-lines=1 \
      --bind 'enter:execute-multi(sh fzf_images _fzf_images_action_load {1})+abort'
}

# ! set this to run on fzf-tmux -p
# ! push image to remote
# ! image rm
_fzf_images_fzf_local(){
  $FZF_IMAGES_CLIENT images | fzf \
    --multi \
    --header-lines=1 \
      --bind 'enter:execute-silent(sh fzf_images _fzf_images_action_run {3})+abort' \
    --preview-window right,60% \
    --preview 'sh fzf_images _fzf_images_preview_inspect {3} | bat --plain -l json'
}

#####################
### ACTION
#####################

# ! echo $LOADED from the fzf process but to the tmux pane? goal is to only see the output
_fzf_images_action_load(){
  for i in $(echo "$@" ); do 
    # LOADED+="$($FZF_IMAGES_CLIENT load -i $i)\n"
    $FZF_IMAGES_CLIENT load -i $i
  done
  # tmux send-keys "echo -e \"$LOADED\""
}

_fzf_images_action_run(){
  export $(tmux showenv | grep '^FZF_IMAGES_REGISTRY')
  PORT=$(tmux showenv | grep '^FZF_IMAGES_PORT' | awk -F '=' '{print $2}')
  if [[ -z "$PORT" ]]; then
    COMMAND="run -ti --rm"
  else
    COMMAND="run -ti --rm -p $PORT:$PORT"
  fi
  tmux send-keys "$FZF_IMAGES_CLIENT $COMMAND $FZF_IMAGES_REGISTRY$1" Enter
  tmux setenv -u FZF_IMAGES_PORT
}

#####################
### PREVIEW
#####################

# ! tee save multiple values to array
_fzf_images_preview_inspect(){
  FZF_IMAGES_PREVIEW_LOCAL=$($FZF_IMAGES_CLIENT inspect $1)
  { PORT=$( echo "$FZF_IMAGES_PREVIEW_LOCAL" | tee /dev/fd/3 | \
    jq -r '.[].Config.ExposedPorts | keys[]' | \
    awk -F "/" '{print $1}'); \
  } 3>&1
  tmux setenv FZF_IMAGES_PORT $PORT
}

#####################
### HELPERS
#####################

# note: doesn't show untagged images because no [] sending error to /dev/null
# ! show size in MB
# ! split PUSHED by date/time
# ! sort based on date/time in descending order
_fzf_images_tags_registry(){
  if [[ ! -z "$1" ]]; then _fzf_images_auth_registry $1; fi
  mkdir -p $FZF_IMAGES_TAGS_REGISTRY_DIR
  FZF_IMAGES_TAGS_REGISTRY_FILE=$FZF_IMAGES_TAGS_REGISTRY_DIR/$1

  if [[ -f "$FZF_IMAGES_TAGS_REGISTRY_FILE" ]]; then
    cat $FZF_IMAGES_TAGS_REGISTRY_FILE
  else
    FZF_IMAGES_REGISTRY_REPOS=$(aws ecr describe-repositories --region $AWS_REGION | \
      jq -r ".repositories[].repositoryName")
    for repo in ${FZF_IMAGES_REGISTRY_REPOS[@]} ; do
      FZF_IMAGES_REGISTRY_IMAGES+="$(aws ecr describe-images --repository-name $repo --region $AWS_REGION | \
        jq -r '.imageDetails[] | "\(.repositoryName) \(.imageTags[]) \(.imagePushedAt) \(.imageSizeInBytes)"' 2>/dev/null)\n"
    done
    echo -e "$FZF_IMAGES_REGISTRY_IMAGES" | \
      sort | sed '1i REPOSITORY TAG PUSHED SIZE' | column -t | \
      tee $FZF_IMAGES_TAGS_REGISTRY_FILE
  fi
}

_fzf_images_get_registry(){
  if [[ $FZF_IMAGES_CLIENT == "podman" ]]; then
    AUTH_FILE=~/.config/containers/auth.json
  elif [[ $FZF_IMAGES_CLIENT == "docker" ]]; then
    AUTH_FILE=~/.docker/config.json
  fi
  cat $AUTH_FILE | jq -r '.credHelpers | keys[]'
}

# note: this assumes that theres a profile defined in .aws/credentials in the format [ACCOUNT_*]
_fzf_images_auth_registry(){
  FZF_IMAGES_REGISTRY_AWS_ACCOUNT=$(echo "$1" | awk -F '.' '{print $1}')
  FZF_IMAGES_REGISTRY_AWS_PROFILE=$(cat ~/.aws/credentials | \
    grep -o -P "(?<=\[)$FZF_IMAGES_REGISTRY_AWS_ACCOUNT.*(?=\])")
  AWS_PROFILE=$FZF_IMAGES_REGISTRY_AWS_PROFILE
}

$@
